apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nope 
  janus-idp.io/tekton: nope
  backstage.io/kubernetes-id: nope
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nope
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  