apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nope-gitops
  description: This is GitOps manifest for nope   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nope
    janus-idp.io/tekton: nope 
    backstage.io/kubernetes-id: nope 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nope
