apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nope
  janus-idp.io/tekton: nope
  backstage.io/kubernetes-id: nope
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nope
resources: 
- deployment.yaml
- route.yaml
- service.yaml
